import './globals.css'
import { Inter } from 'next/font/google'
import Newside from '@/components/Newside';
import Exp from '@/components/Exp';
import Layout from '@/components/shared/Layout';

// import DashboardStatsGrid from '@/components/DashboardStatsGrid';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Newside/> */}
      {/* <Exp/> */}
      <Layout/>
      {/* <DashboardStatsGrid /> */}
        {children}</body>
    </html>
  )
}
